name: Deploy Hello World Nginx to k3s

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nihallondhe/nginx-k3s:latest .
          docker push nihallondhe/nginx-k3s:latest

    
     
