name: Deploy Hello World Nginx to k3s

on:
  push:
    branches:
      - main  # Trigger on main branch push

jobs:
  deploy:
    runs-on: self-hosted  # Run on your self-hosted k3s runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="nihallondhe/nginx-k3s:latest"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Update Kubernetes Manifest
        run: |
          sed -i 's|image: nihallondhe/nginx-k3s:.*|image: nihallondhe/nginx-k3s:latest|g' nginx-hello-world.yaml

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f nginx-hello-world.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc hello-nginx-service
